const ui = {
  navigation: {
    home: 'Home',
    about: 'About',
    work: 'Work',
    education: 'Education',
    skill: 'Skills',
    skills: 'Skills',
    portfolio: 'Portfolio',
    hobbys: 'Interests',
    interests: 'Interests',
    certification: 'Certifications',
    certifications: 'Certifications',
    testimonials: 'References',
    references: 'References',
    photo: 'Photo',
  },
  navMenu: {
    showNav: 'Show navigation',
    hideNav: 'Hide navigation',
  },
  hero: {
    viewResume: 'View Resume',
    contactMe: 'Contact Me',
    scroll: 'Scroll',
    statsYears: 'Years Experience',
    statsTech: 'Technologies',
    statsCountries: 'Countries',
  },
  sections: {
    about:         { eyebrow: 'About',          title: 'About Me' },
    work:          { eyebrow: 'Experience',      title: "Where I've Built Things" },
    education:     { eyebrow: 'Education',       title: 'Academic Background' },
    skills:        { eyebrow: 'Skills',          title: 'What I Work With' },
    languages:     { eyebrow: 'Languages',       title: 'Languages I Speak' },
    interests:     { eyebrow: 'Interests',       title: 'Beyond the Keyboard' },
    portfolio:     { eyebrow: 'Portfolio',       title: "Things I've Shipped" },
    certifications:{ eyebrow: 'Certifications',  title: 'Credentials' },
    references:    { eyebrow: 'References',      title: 'What Others Say' },
    softSkills:    { eyebrow: 'Interpersonal',   title: 'Soft Skills' },
  },
  work: {
    present: 'Present',
    current: 'Current',
    title: 'Work',
    showMore: '↓ Show {count} earlier {label}',
    showMoreSingle: '↓ Show {count} earlier position',
    showMorePlural: '↓ Show {count} earlier positions',
    showLess: '↑ Show less',
    employmentTypes: [
      { value: 'Full-Time',       label: 'Full-Time' },
      { value: 'Part-Time',       label: 'Part-Time' },
      { value: 'Working Student', label: 'Working Student' },
      { value: 'Mini Job',        label: 'Mini Job' },
      { value: 'Other',           label: 'Other' },
    ],
  },
  about: {
    title: 'About Me',
    subtitle: 'Contact Details',
    openBadge: 'Open to opportunities',
    yearsExp: '{years}+ years experience',
  },
  skills: {
    title: 'Skills',
  },
  modal: {
    details: 'Details',
    close: 'Close',
  },
  certification: {
    title: 'Certifications',
    verify: 'Verify',
  },
  education: {
    title: 'Education',
    present: 'Present',
    gradeLabel: 'Grade',
    gradeScaleTitle: 'German Grading Scale',
    thesisLabel: "Master's Thesis",
  },
  hobbys: {
    title: 'Interests',
  },
  references: {
    title: 'References',
    moreNote: 'Need more? Additional references available on request.',
    requestBtn: 'Request a reference letter',
    requestSubject: 'Reference%20Request',
    requestBody: 'Hi%2C%20I%20would%20like%20to%20request%20a%20reference%20letter.',
  },
  gradeScale: {
    veryGood: 'Excellent',
    good: 'Good',
    satisfactory: 'Satisfactory',
    sufficient: 'Sufficient',
    fail: 'Fail',
  },
  print: {
    saveButton: 'Save PDF',
  },
  theme: {
    toggleLabel: 'Toggle theme',
  },
  footer: {
    description: 'Designed and built in React.js by {author1}',
    authorName: 'Tazbirul Haque',
  },
}

export default ui
